### ISSUE TITLE
Все идеи какие-то беззубые

### ISSUE THREAD

**Issue by dmikushin** [developers-against-repressions/devs-against-the-machine#20]
Ребята, не хочу никого обидеть, но: все идеи какие-то беззубые. Понимаю, что вы умеете и любите верстать экраны и рисовать инфографику. Это всё годилось для робких 2011-2012 годов. Тогда власть не умела работать в сетях, а сейчас даже ДИТ г. Москвы [пробует](https://www.cnews.ru/news/top/2019-11-08_vlasti_moskvy_potratyat_1) считать большие данные на графических процессорах. И это лишь вершина айсберга, возможно кто-то всё-таки читал о более серьёзных [системах](https://meduza.io/feature/2019/08/08/maksimalnoe-kolichestvo-kompromata-na-vseh).

Короче говоря, моё личное мнение: в мире машинного обучения кнопочками и графиками вы никого не защитите. Необходимы средства защиты актуального уровня: генераторы информационных помех, личные гаджеты для защиты и для сбора информации. Финансовые инструменты для донатеров и штабов. Более совершенные расследовательские коптеры, в конце концов! Давайте брать выше.

**Comment by KlonD90** [comment]
Давайте без осуждения отдельного, но можно в общей теме про идеи как задать вектор + прокомментировать каждый issue отдельно на конкретике. Выстрелить может все что угодно, да и массовость явления тут может быть важнее чем конкретные результаты. Пока разгоняем идеи может быть, что любая идея придет к какой-нибудь, которая будет много эффективнее.

Предлагаю переделать issue в сторону мета тему для сбора идей такого направления.
