### ISSUE TITLE
Идея: попытаться согласовать с ОВД-инфо приложение для предоставления необходимой информации при задержании

### ISSUE THREAD

**Issue by ivalosta** [developers-against-repressions/devs-against-the-machine#28]
возможный набор функций:
* красная кнопка при задержании скидывает местоположение, ФИО и дату рождения
* интерактивная карта задержаний
* интерактивная карта передвижения полиции во время протестов
* интерактивная карта по отделениям, для вызова адвокатов и необходимости передач

**Comment by loalexandra** [comment]
здравствуйте, загляните пожалуйста сюда и в чат 
https://github.com/developers-against-repressions/devs-against-the-machine/issues/30

**Comment by ivalosta** [comment]
не буду тогда захламлять)
