### ISSUE TITLE
Реализованный проект: игра «Пиксельки»

### ISSUE THREAD

**Issue by Matovsky** [developers-against-repressions/devs-against-the-machine#32]
Я уже писал о своей игре. Она **совсем новая и очень тематическая для хакатона**. Так вот, что я хочу изменить/дополнить во время хакатона. Большинство смотрит рекламу во время игры на телефоне (для получения бонусов, жизней и пр) вместо приобретения встроенных покупок. Поэтому **самое основное изменение/дополнение которое я хотел бы сделать во время хакатона, это передать аккаунт AdMob (вместе с аккаунтом Google) тем кто собирает деньги на арестованных по московскому делу**. Ну и потом для других нужд. Я очень сомневаюсь что это последние массовые аресты. **Игра и так уже более чем тематическая, так ещё и будет инструментом для пожертвований.**
Игра доступна только для iPhone/iPad. Ссылка в App Store: https://apps.apple.com/ru/app/id1477697149

**Comment by KlonD90** [comment]
Ну нет спонсировать это уже частное дело каждого. Можете сделать какой-то мод для игры в поддержку или новый контент в рамках хакатона. Может хотели давно что-то улучшить но не доходили руки?

**Comment by Matovsky** [comment]
Вы тогда определитесь пожалуйста нужно или нет. Одни организаторы говорят что можно. Другие что это моё личное дело и к хакатону не относится. А то выглядит как будто я выпрашиваю участие и желание стать благотворителем.

**Comment by Matovsky** [comment]
Раз никому реальная помощь посредством тематической игры оказалась не нужна, я снимаю игру с участия. Всем большое спасибо.
