### ISSUE TITLE
Обязательно ли представлять проекты, сделанные во время хакатона?

### ISSUE THREAD

**Issue by CORRUPTOR2037** [developers-against-repressions/devs-against-the-machine#5]
У меня есть проект по теме, достаточно большой, делаю уже давно, но он ещё в разработке и за пару дней его не доделать. Хотелось бы его предоставить.
Согласен участвовать вне конкурса

**Comment by KlonD90** [comment]
Привет! Мне кажется это круто и в любом случае про него рассказать здесь, но я не уверен что это часть хакатона как такого.

**Comment by fersel** [comment]
Думаю, этот хакатон -- в том числе хороший шанс рассказать о проекте и, возможно, найти единомышленников, которые помогут его реализовать (если есть такое желание).

Для полноценного участия можно попробовать выделить часть проекта, которая будет реализована конкретно в рамках хакатона и/или сопроводить работу дисклеймером о том, что разработка велась ещё до хакатона.

В любом случае мы -- и, думаю, более широкая аудитория -- будем рады познакомиться с проектом :)

**Comment by CORRUPTOR2037** [comment]
Спасибо
Я постараюсь вынести одну задачу исключительно на хакатон
Дисклеймер и отказ от призового места будет сопровождён при сдаче проекта
