### ISSUE TITLE
Идея: дашборд с суммой по хищениям и суммой, необходимой для операций благотворительным фондам по подобию http://zenrus.ru/

### ISSUE THREAD

**Issue by ivalosta** [developers-against-repressions/devs-against-the-machine#55]

**Comment by taranoff** [comment]
Вообще, идея интересная. Я готов помочь с фронтом / бэком. Но я абсолютно нулевой дизайнер.

Можно было бы представить такой дашборд "карту" наших коррупционеров. В центре самые крупные (например в кружках) к краям помельче. При щелчке на кружке - краткий список хищений, рядом с каждым из них - пометка - 1/ххх этой суммы хватило бы на лечение ххх - со ссылкой на сайт фонда/кейса.

Нужна помощь в сборе данных о коррупционерах / фондах / кейсах сбора средств.

Ну и дизайнер очень нужен. С острым чувством прекрасного.

Предполагаемый стек (Nuxt.js pre-render).
