### ISSUE TITLE
Идея: сервис для оповещений о передвижениях полиции/задержаниях/перегруппировках на протестных акциях

### ISSUE THREAD

**Issue by ololosha228** [developers-against-repressions/devs-against-the-machine#58]
**Проблема:** мы все помним, что было на цветном бульваре 27 июля: люди остановились на площади, менты закрыли всех в кольцо, началось винтилово. Одна из причин, почему это произошло — недостаточная информированность людей на протестных акциях, где конкретно находятся полицейские и росгвардия, и что они собираются сделать

**Суть:** было бы неплохо иметь приложение, или бота, которому можно отослать лайв геометку о твоем местонахождении, и получать информацию о том, что происходит вокруг  тебя, а не весь информационный поток (инфы-то много, а сидеть все время в телефоне — плохая стратегия). Справа на перекрестке оцепление? Тогда возвращаемся назад. А, сзади тоже давят синекрасные? окей, тогда передислоцируемся в парк, что слева от перекрестка. Так победим.

Да и к тому же: если ты вышел из зоны протестов не по своей воле (например, автозак уже везет тебя в рандомное овд), бот/приложение может спросить, все ли с тобой в порядке, и если ты не отвечаешь, либо нажимаешь кнопку "нет", информируются все твои близкие контакты, что с тобой, и где ты.

**Что решает проект:** более плотное информирование протестных шествий о происходящем вокруг них, повышение коннективити между участниками, сбор общей статистики о эффективности протестов, что, кстати, улучшит подготовку к последующим акциям.

**Что НЕ решает проект:** ухудшение коннективити в толпе в момент шатдауна. К счастью, на хакатоне представлены другие проекты по решению этой проблемы.

[пулл реквест проекта](https://github.com/developers-against-repressions/devs-against-the-machine/pull/57)
[репозиторий проекта](github.com/xelaj/mcclane)

**Comment by quenbyako** [comment]
Закрываю таск, т.к. уже есть реализация, которую мы поддерживаем.
