### ISSUE TITLE
Репозиторий: структура добавления проектов

### ISSUE THREAD

**Issue by ololosha228** [developers-against-repressions/devs-against-the-machine#8]
Предлагаю воспользоваться всеми прелестями гита, и вместо добавления файлов с проектами, давайте добавлять субмодули репизотриев, созданых на github или gitlab?
Мне кажется, что это более удобно, чем файлы с ссылками, поскольку таким образом намного проще менеджерить репозитории как организаторам, так и участникам

Как это сделать:

Склонируем репозиторий, перейдем в папу `./projects`
``` sh
git clone git@github.com:developers-against-repressions/devs-against-the-machine.git
cd ./devs-against-the-machine/projects
```
Далее нужно добавить подмодуль в репозиторий, подмодуль должен быть уже заранее закоммичен на github/gitlab/bitbucket/ваш-личный-репозиторий **remote должен быть** `origin` **а ветка** `master` (что бы никто из команд-участников потом не запутался). добавление в этот репозиторий может происходить так:
``` sh
git submodule add <ваша ссылка на репозиторий>
git add . 
git commit -m "добавлен репозиторий команды <ваше название>"                        
```

Всё. теперь подмодуль будет надежно храниться в общем репозитории :)
Но обновлять все нужно в ручную (особенность гита). Для того что бы все проекты были up-to-date в вашей директории, можно запустить команду:
``` sh
git submodule foreach git pull
```
Что скажете на это предложение?

**Comment by KlonD90** [comment]
Пока кажется перебором уж больно жирно репозиторий получится если все хорошо пойдет. Потом скачивание сабмодулей ни к чему не приведет. Но какого-нибудь бота который обойдет и соберет README.md вполне можно.

**Comment by ololosha228** [comment]
Дело в том, что даже если каждый репозиторий будет весить по 5 мегабайт, а участников будет 200-300, то если очень захочется скачать все репозитории, больше 1.5гб не будет по любому. в любом случае, ссылки нужно проверять что они валидны.

Но, в общем то я согласен, что просто так весь репозиторий качать нет смысла

**Comment by loalexandra** [comment]
Закрою, потому что решили не делать
