### ISSUE TITLE
Не позорьтесь 

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [developers-against-repressions/devs-against-the-machine#95]
На прекрасное айти вы уже попали - https://ebanoe.it/2019/12/16/hackathon-for-every-issue/

Теперь по существу:  не лезьте своими костлявыми нежными пальчиками в тему, с которой вы не знакомы. _"Онлайн-хакатон в поддержку полизаключенных"_? С таким же успехом в поддержку политзаключенных можно на шашлыки сходить, поесть колбаски в поддержку политзаключенных, выпить водочки в поддержку политзаключенных или совершить иное дело себе во благо, ради своего удовольствия, не вылезая из своей уютной мещанской коробки, и при этом аргументируя это действие "в поддержку" кого-либо. 

Хочешь помочь политзаключенным - выйди на улицу, на митинг, в одиночный пикет, прикуй себя наручниками к зданию суда и т.д. Слабо? Я знаю, что **_вам_** слабо. Так если слабо - не хайпуйте на этой теме, не лезьте туда, где пахнет кровью, [бейсбольными битами](https://ru.wikipedia.org/wiki/%D0%A7%D0%B5%D1%80%D0%B2%D0%BE%D1%87%D0%BA%D0%B8%D0%BD,_%D0%AE%D1%80%D0%B8%D0%B9_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87#%D0%A3%D0%B1%D0%B8%D0%B9%D1%81%D1%82%D0%B2%D0%BE), вонючими обезьянниками и прессом органов.

**Comment by KlonD90** [comment]
Ну такое. Большинство из нас и так выходит на протесты и другими способами участвуют в гражданской активности.

Не спорю, что такая критика имеет место быть, но больше похоже на перенос чужих проблем на участников.
